server:
  port: 9090



#=================================================================================
# spring 组件相关设置

spring:
  datasource:
    url: jdbc:mysql://47.244.38.7:3307/test?rewriteBatchedStatements=true&useUnicode=true&characterEncoding=utf-8&characterSetResults=UTF-8&autoReconnect=true&allowMultiQueries=true&useSSL=false
    username: root
    password: wind